### ISSUE TITLE
Installation of unigd fails

### ISSUE THREAD

**Issue by certara-tzweers** [nx10/unigd#18]
I'm working on a windows system and I'm trying to install the httpgd package. Httpgd is not on CRAN at the moment, but I tried to install the development version. This fails because unigd fails to compile.

When I try to install unigd with remotes::install_github("nx10/unigd") it fails compilation with the below feedback:
C:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: cannot find -lsharpyuv
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'unigd'

When I try to install unigd from CRAN I get the same error (there is no compiled version on CRAN).

### Environment
 - OS: Windows 10
 - R version: 4.2.3
 - unigd version: 0.1.0
 

I cannot be sure this is because of issues with rtools on my system but last month I installed httpgd on this same system without problems and I have no problems installing/compiling other r packages.

### Solution
I was able to install the packages through r-universe without a compile being necessary.

`install.packages('httpgd', repos = c('https://nx10.r-universe.dev', 'https://cloud.r-project.org')) `

**Comment by ericnewkirk** [comment]
Thank you for posting your solution! This saved me a ton of time battling with `renv` to get a project set up in vs code.

**Comment by nx10** [comment]
Both unigd and httpgd are on CRAN now
