### ISSUE TITLE
Release with TIFF renderer

### ISSUE THREAD

**Issue by benz0li** [nx10/unigd#20]
Cross reference: https://github.com/nx10/httpgd/issues/145#issuecomment-1928158396

Thank you @nx10.

**Comment by nx10** [comment]
Thank you again for your PR. Just submitted 0.1.1 will close upon acceptance.

**Comment by benz0li** [comment]
unigd v0.1.1 was rejected. What were the reasons?

**Comment by nx10** [comment]
Their system said the unit tests are failing under windows and sent a report with all of them passing correctly... I sent them an email.

**Comment by nx10** [comment]
It was an issue on their side. On its way to CRAN now
