### ISSUE TITLE
Transparent background in SVG?

### ISSUE THREAD

**Issue by raymondben** [nx10/unigd#7]
### Describe the bug

Not sure if this is a bug or my misunderstanding. SVG is not being given a transparent background when asked.

### To Reproduce

This works, png has a transparent background:
```
temp <- airquality$Temp
ugd_save_inline(hist(temp), file = tempfile(fileext = ".png"), as = "png", background = "transparent")
```

This does not, SVG has a white background:
```
ugd_save_inline(hist(temp), file = tempfile(fileext = ".svg"), as = "svg", background = "transparent")
```

Inspecting the generated svg, I see that there is a `<rect>` element with width and height 100% and white fill. If I set that fill to "none" by editing the svg output, the background is transparent as expected (or that rect element can be deleted entirely). But I can't set `ugd_save_inline(... bg = "none")` because it complains about an `invalid color name 'none'`.

Also, setting bg to anything with alpha, the alpha gets ignored (so e.g. `ugd_save_inline(... bg = "#FFFFFF00")` also does not work). Should there be a `color::alpha(t_page.fill)` element appended on https://github.com/nx10/unigd/blob/master/src/renderer_svg.cpp#L221 ?

### Expected behavior

I'd expect a transparent background in the SVG.

### Environment

unigd_0.1.0.9000

```
> sessionInfo()
R version 4.3.2 (2023-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.6 LTS
```

**Comment by nx10** [comment]
Thanks for raising this issue! This should work now.
